# Escutar na porta padrão
listener 1883

# Permitir acesso sem user/pass (protegido pelo túnel Tailscale)
allow_anonymous true

# Persistência de dados (essencial para quando ligares o InfluxDB)
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest file /mosquitto/log/mosquitto.log
